---
- name: Install dependencies
  package:
    name: curl
    state: present
  when: ansible_os_family in ["Debian", "RedHat"]

- name: Download Pushgateway
  get_url:
    url: "{{ pushgateway_url }}"
    dest: "/tmp/pushgateway.tar.gz"
    mode: "0644"

- name: Extract Pushgateway
  ansible.builtin.unarchive:
    src: "/tmp/pushgateway.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Move Pushgateway binary
  command: mv /tmp/pushgateway-{{ pushgateway_version }}.linux-amd64/pushgateway {{ install_dir }}/pushgateway
  args:
    creates: "{{ install_dir }}/pushgateway"

- name: Ensure Pushgateway is executable
  file:
    path: "{{ install_dir }}/pushgateway"
    mode: "0755"

- name: Create systemd service file
  template:
    src: pushgateway.service.j2
    dest: "{{ service_file }}"
  notify: Restart Pushgateway

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Pushgateway
  systemd:
    name: pushgateway
    enabled: yes
    state: started
