---

- name: Erstelle temporären Download-Ordner
  ansible.builtin.file:
    path: /tmp/grafana
    state: directory
    mode: '0755'

- name: Lade Grafana herunter
  ansible.builtin.get_url:
    url: "https://dl.grafana.com/enterprise/release/grafana-enterprise-{{ grafana_version }}.linux-amd64.tar.gz"
    dest: "/tmp/grafana/grafana.tar.gz"
    mode: '0644'

- name: Entpacke Grafana
  ansible.builtin.unarchive:
    src: "/tmp/grafana/grafana.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Erstelle Systemd-Service für Grafana
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ grafana_service_name }}.service"
    content: |
      [Unit]
      Description=Grafana Service
      After=network.target

      [Service]
      Type=simple
      User=root
      ExecStart=/opt/grafana/bin/grafana server --homepath=/opt/grafana --config=/opt/grafana/conf/defaults.ini
      Restart=always

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Systemd neu laden
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Aktiviere und starte den Grafana-Dienst
  ansible.builtin.systemd:
    name: "{{ grafana_service_name }}"
    enabled: yes
    state: started

- name: Erlaube HTTP-Zugriff in der Firewall (Port 3000)
  ansible.builtin.firewalld:
    port: 3000/tcp
    permanent: yes
    state: enabled
    immediate: yes

